import os
from setuptools import setup, find_packages

setup(
    name='ComplexNetworkOperation',
    version='0.0.1',
    # packages=find_packages(where='complex_network_operation_py', exclude=['tests', 'docs', 'examples']),
    packages=find_packages(),
    # package_dir={'': 'complex_network_operation_py'},
    install_requires=[
        'numpy',
        'pandas',
        'networkx',
        'matplotlib',
        # 'logging',
        # 'pickle',
        # 'typing',
        # 'functools',
        # 'random',
        # 'string',
        # 'locale',
        # 'subprocess',
        # 'base64',
        # 'multiprocessing',
        'noise',
        'chardet',
        # 'numba',
        # 'cv2',
        # 'scipy',
        # 'igraph',
        # 'drawsvg',
        # 'fitz',
        # 'svglib',
        # 'reportlab',
    ],
    author='Complex System Explorer',
    author_email='',  # TODO
    description='Python版本的复杂网络运作库。',
    long_description=open('README.md').read() if os.path.exists('README.md') else '',
    long_description_content_type='text/markdown',
    url='https://github.com/ComplexSystemLab/ComplexNetworkOperation.git',
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.12.1',
    license='MIT',
)
